platform :ios, '8.0'

target 'jscnative' do
pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
pod 'React', path: '../node_modules/react-native/'
pod 'React', path: '../node_modules/react-native/', :subspecs => [
'BatchedBridge',
]
pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/ios/'
end